//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcPL.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MvcPL.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account does not exist.
        /// </summary>
        internal static string AccountNotFount {
            get {
                return ResourceManager.GetString("AccountNotFount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account is not closed. Please try again..
        /// </summary>
        internal static string CloseAccountInvalid {
            get {
                return ResourceManager.GetString("CloseAccountInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input deposit value does not valid.
        /// </summary>
        internal static string DepositValueNotValid {
            get {
                return ResourceManager.GetString("DepositValueNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accounts number are duplicated. Please chose different accounts number..
        /// </summary>
        internal static string DublicatedNumberAccount {
            get {
                return ResourceManager.GetString("DublicatedNumberAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email is not correct. Please try again..
        /// </summary>
        internal static string EmailIsNotValid {
            get {
                return ResourceManager.GetString("EmailIsNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to should not be a empty.
        /// </summary>
        internal static string EmptyString {
            get {
                return ResourceManager.GetString("EmptyString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First name is not correct. Please try again..
        /// </summary>
        internal static string FirstNameIsNotValid {
            get {
                return ResourceManager.GetString("FirstNameIsNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input value does not valid. Please try again input..
        /// </summary>
        internal static string InvalidInputValue {
            get {
                return ResourceManager.GetString("InvalidInputValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For close account you must check checkbox &quot;State&quot;. Please check checkbox and try again..
        /// </summary>
        internal static string InvalidStateAccountForClose {
            get {
                return ResourceManager.GetString("InvalidStateAccountForClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last name is not correct. Please try again..
        /// </summary>
        internal static string LastNameIsNotValid {
            get {
                return ResourceManager.GetString("LastNameIsNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You do not have accounts yet. Please create new account and try again..
        /// </summary>
        internal static string NotExistAccounts {
            get {
                return ResourceManager.GetString("NotExistAccounts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argument is null.
        /// </summary>
        internal static string NullArgument {
            get {
                return ResourceManager.GetString("NullArgument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passport number is not correct. Please try again..
        /// </summary>
        internal static string PassportNumberIsNotValid {
            get {
                return ResourceManager.GetString("PassportNumberIsNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to should not be a whitespace.
        /// </summary>
        internal static string WhiteSpaceString {
            get {
                return ResourceManager.GetString("WhiteSpaceString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input withdraw value does not valid.
        /// </summary>
        internal static string WithDrawValueNotValid {
            get {
                return ResourceManager.GetString("WithDrawValueNotValid", resourceCulture);
            }
        }
    }
}
